### ISSUE TITLE
crash on entering a mystcraft age

### ISSUE THREAD

**Issue by darkmdbeener** [Quetzi/Morpheus#10]
When someone enters a statecraft age, the server will crash. The server is ok to restart and ok when playing. The server then kicks out the player when they try to enter the age.

attached are the crash reports if that is helpful. the mystcraft being used is the one in direwolf 1.3.1

http://pastebin.com/xRQqi6CS

http://pastebin.com/ZQqHFzuQ

XCompWiz told me it seems to be morpheus causing the crash.
https://github.com/XCompWiz/Mystcraft-Issues/issues/82

**Comment by Quetzi** [comment]
> The server then kicks out the player when they try to enter the age.

A log/stacktrace showing this would be handy, I suspect there is an issue with the dimension no longer existing or something. Does this happen with every Mystcraft age or just one specific one?

**Comment by darkmdbeener** [comment]
every one. how would I provide you with stacktrace?

**Comment by Quetzi** [comment]
pastebin the relevant log section would be fine.

**Comment by darkmdbeener** [comment]
I do apologize, but I dont know where I would fine that all that I see when it crashes is the crash file. is there another file I should be looking for.

**Comment by Quetzi** [comment]
if the client is being kicked off and the server stays online then the crash i need could be on the client. In short, I think some other mod is doing something wrong and my mod crashing is a result of that. The code that is crashing hasn't changed since October and this is the first stacktrace like this I've had, it must be something else.

**Comment by darkmdbeener** [comment]
ok let me force a crash and see if I can find the file,
 thank you.

**Comment by darkmdbeener** [comment]
http://pastebin.com/qedN5s6r

http://pastebin.com/LbmGK9g0

http://pastebin.com/75zBaJtE

these are the client side reports.

**Comment by Quetzi** [comment]
Those look like the kind of crashes I'd expect to see if dimension data had been deleted. They reference Funky Locomotion, though I suspect these crashes are more familiar looking to @XCompWiz

**Comment by XCompWiz** [comment]
Not data, registration.  The dimension registration is missing for the dimension.
Either the dimension doesn't exist on the server, or the client isn't getting the dimension information before the login info.
Do you have a an agedata_2.dat file in the data folder on the server save?

**Comment by darkmdbeener** [comment]
I did not see that file in world/data or world/

**Comment by XCompWiz** [comment]
Seems like the player managed to get to a dimension that doesn't exist.  Perhaps the easiest method is to try to create the dimension.  Either /myst-create 2 or by using a Descriptive book.  The latter method might not create dimension 2, however.

Note that the ORIGINAL crash reports were for the server and timed for about when the dimension was created, so it's possible that broke the dimension saving.  The client getting kicked off is a side effect of the original crash.

We still need the actual log from when the server crash occurs.  These new crash reports are a symptom, not the root problem.

**Comment by darkmdbeener** [comment]
http://pastebin.com/xRQqi6CS this one was the only crash report that showed up when it first crashed.

**Comment by XCompWiz** [comment]
Not crash log, jut normal running log. The fml-client-latest.log file in the logs folder.
You'll need to recreate the crash and grab that file.

**Comment by darkmdbeener** [comment]
ok will do.

**Comment by darkmdbeener** [comment]
So .... after doing /myst-create 2 That crash can not be reproduced. He is able to create ages at will with no crash. so... odd.
