### ISSUE TITLE
Witchery Support

### ISSUE THREAD

**Issue by SephirothWS** [Quetzi/Morpheus#11]
As you may or may not know, Witchery has a mechanic known as Vampirism. It allows players to sleep during the day to make it night.

Right now Morpheus confuses that with its sleep voting and causes daytime sleeping to simply reset the time to the next morning. Would it be possible to detect if sleeping during the day, and thus make it night instead of day?

**Comment by Quetzi** [comment]
This is something that needs to be done on Witcherys side. I've explained already to Emoniph how this can be done.

**Comment by Eufranio** [comment]
https://sites.google.com/site/witcherymod/faq

> Q: Do vampires work with the Morpheus mod?
> A: No, in general a server that has vampires enabled (you can disable access to this feature), will want to ensure that both vampire players and non-vampire players have sufficient safe play time (day for normal players, night for vampires). Mods like Morpheus that allow non-vampires to force daytime without vampire players consent, can cause descent. It is recommended if enabling the vampire feature to consider the necessity for night. See the previous question for how to stop vampire witches forcing night all the time.
