### ISSUE TITLE
1.7.10 - Other dims.

### ISSUE THREAD

**Issue by Kasparsun** [Quetzi/Morpheus#18]
Hey

Is there anyway to make this work in other Dims then "world", as we are runing a server where we dont use the normal "world" but a costume made one. the mod works in the normal "overworld", but in the other dim that we use as our main world.

Thanks
Kaspar

**Comment by Quetzi** [comment]
Yes, Morpheus fully supports custom dimension mods. All they need to do is register their dimension with Morpheus and the sleep vote will work as normal. If your custom dimension doesn't currently support Morpheus you should report it to that mods author.

**Comment by Kasparsun** [comment]
what about plugins?, since our dim. is created by a plugin called "askyblock"

http://dev.bukkit.org/bukkit-plugins/skyblock/

**Comment by Quetzi** [comment]
I wouldn't expect any kind of support to be possible, honestly. From my side I have no idea and no way of checking what the day night cycles are for custom worlds so rely on them being registered with my api. If that plugin can do that then I see no reason why it wouldn't work. In any case, support is on them.

**Comment by Kasparsun** [comment]
Thanks
