### ISSUE TITLE
FTB Beyond: Sleep voting config percentages not working in other dimensions

### ISSUE THREAD

**Issue by DingoX3** [Quetzi/Morpheus#30]
We have a main world, which is the mining Dim. Then we made another Dim for free-build/base building. In the main world(mining dim) 25% works fine. In The alternate Dim(free-build/base building) no matter what percentage it goes to it never passes to day. Is there a way to get morpheus to recognize the configs for the other dims?

minecraft version 1.10.2
forge 12.18.3.2254
morpheus 1.10.2-3.1.13
modpack FTB Beyond

**Comment by Quetzi** [comment]
This is because Aromas dimensional world hasn't implemented Morpheus compat. @aroma1997 just needs to implement and register a class for it to work.

**Comment by Aroma1997** [comment]
I'll look into it. (Although with the default config setting, it should never be night-time in the mining world)
