### ISSUE TITLE
servercrash, java.lang.NullPointerException: Exception in server tick loop 	at net.quetzi.morpheus.helpers.SleepChecker.updatePlayerStates

### ISSUE THREAD

**Issue by i9hdkill** [Quetzi/Morpheus#31]
Forge 2254
Morpheus: 3.1.13
FTB Beyond

Guess because the player logged out, the couldn't update the player state? 

mc crashlog:
https://pastebin.com/Hh16gCCs
error in forge log:
https://pastebin.com/Y05emFJF

**Comment by Quetzi** [comment]
Sponge issue, wait for a fix from them.
