### ISSUE TITLE
Server Crash While Teleporting Through Dimensions

### ISSUE THREAD

**Issue by EZKatnipz** [Quetzi/Morpheus#34]
Server crash when using Draconic Evolution Dislocator, teleporting from Nether to Overworld. No other players online.
Happened once, created Issue. Haven't tested more yet.

https://pastebin.com/ZWGTmJV3

**Comment by Quetzi** [comment]
Sponge bug. To fix, use a forge server

**Comment by EZKatnipz** [comment]
Alright, so this is an issue because of Sponge, and it should be fixable in Sponge, correct? Is it worth it to make a bug report for Sponge? And from what you've seen, would this be all the information that would be needed for the Sponge Devs to maybe take a look?
Not asking for anything more than just your opinion, not asking you to take a look into anything.

**Comment by Quetzi** [comment]
There is already an issue open there
