### ISSUE TITLE
1.11.2-3.2.14 failing under Forge 2310

### ISSUE THREAD

**Issue by kreezxil** [Quetzi/Morpheus#37]
Discovered some issues where it no longer allows wake to a new day unless everyone has slept at least once that are on the server. It'll say #/## and even given the message for when the percentage is met but not wake the player nor set the day to morning.

Also, while it reads the config to update the messages it gives, it now ignores the percentage. I set my to 20% but in the game it says it's still 50%

Maybe you can add some options to the config that make it generate a debug log that I can feed to you.

**Comment by Quetzi** [comment]
The first situation you describe I'll need to see logs for, not waking the player is a vanilla bug and not related to Morpheus. The second situation sounds like a legitimate scenario in which there are 2 players on the server and is working as intended.

**Comment by kreezxil** [comment]
https://gist.github.com/e9cdb7fff27cff2b590b38b7b3d885f2 @ timecode [13:02:36]
