### ISSUE TITLE
[1.10.2] java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by JaSpr** [Quetzi/Morpheus#38]
It seems to me that it would be fairly simple to check that `Morpheus.playerSleepStatus.get(player.dimension)` did not return null before trying to call `.isPlayerSleeping(username)` on it.  

Quite simply, line 28 of `SleepChecker.java` could be changed from:

```
            else if (!player.isPlayerFullyAsleep() && Morpheus.playerSleepStatus.get(player.dimension).isPlayerSleeping(username))
```

to: 
```
            else if (!player.isPlayerFullyAsleep() && Morpheus.playerSleepStatus.get(player.dimension) != null && Morpheus.playerSleepStatus.get(player.dimension).isPlayerSleeping(username))
```

or an additional layer of nesting could be added, for added readability:

```
            else if (!player.isPlayerFullyAsleep()) {
                    WorldSleepState sleepStatus = Morpheus.playerSleepStatus.get(player.dimension);
                    if (sleepStatus != null && sleepStatus.isPlayerSleeping(username)) {
                        // Do the stuff.
                    }
           }
```

I would be happy to submit a pull request, if it wouldn't be rejected out of hand.

**Comment by Quetzi** [comment]
There is no situation where that should be null so a null check is redundant.

**Comment by john01dav** [comment]
I just got [this](https://www.moddedminecraft.club/crash-reports-beyond/crash-2017-06-17_05.15.43-server.txt) as a crash report on my server, hence there is some situation. Can we get this fixed please?

**Comment by Quetzi** [comment]
Solution: remove sponge (or get them to fix their bug)

**Comment by john01dav** [comment]
What makes you think it is sponge? What, exactly, is there bug?

**Comment by Quetzi** [comment]
Because this only happens when sponge is installed. If you can reproduce this with just forge and Morpheus installed then I'd be interested to see the log for that.

**Comment by john01dav** [comment]
Do you happen to have any advice to reliably reproduce it on Spoge? It
seemed to be happening on my server randomly.

**Comment by Quetzi** [comment]
No, I don't support Sponge so don't test with it.
