### ISSUE TITLE
Crash and burn

### ISSUE THREAD

**Issue by LeChuuck** [Quetzi/Morpheus#39]
Server crashed when i teleport to "Beneath". SkyFactory 3 v.3.0.10

[crash-2017-06-10_13.24.45-server.txt](https://github.com/Quetzi/Morpheus/files/1065804/crash-2017-06-10_13.24.45-server.txt)

**Comment by tolly7654** [comment]
Same issue as issue #21, but with a different modpack.

Seeing as Quetzi shut down issues #21, #35, #34, #33, #32 and #31 because it was a sponge issue (https://github.com/SpongePowered/SpongeForge/issues/830), I would either wait until sponge fixes it or Quetzi decides to support sponge.

**Comment by Quetzi** [comment]
Yep, this is a sponge bug. Pester them to fix it
