### ISSUE TITLE
Crashed With Placement Review Mod(1.12)

### ISSUE THREAD

**Issue by kenijey** [Quetzi/Morpheus#40]
[crash-2017-06-21_13.58.10-server.txt](https://github.com/Quetzi/Morpheus/files/1091281/crash-2017-06-21_13.58.10-server.txt)

**Comment by maruohon** [comment]
This is my fault, my fake world shouldn't end up registered as a real dimension, but I haven't yet fixed/re-factored the code where I create my fake world...

**Comment by kenijey** [comment]
then i'm closing the issue on the other side

**Comment by maruohon** [comment]
You closed the wrong one... This one should be closed, since the issue is in PP.

**Comment by kenijey** [comment]
lol, sorry for that.
