### ISSUE TITLE
1.12 Sleep vote spamming chat

### ISSUE THREAD

**Issue by DingoX3** [Quetzi/Morpheus#41]
http://imgur.com/a/aPua7

minecraft version: 1.12
modpack: ATM3 https://mods.curse.com/modpacks/minecraft/269708-all-the-mods-3
morpheus version: 1.12-3.3.2
forge version: 2387

**Comment by Vazkii** [comment]
This is a quark bug, not Morpheus. The feature in quark is bugged AND should turn off if morpheus is enabled. I forgot to do the latter part though. This issue doesn't belong here, in any case.

**Comment by Vazkii** [comment]
Could you transfer this to Vazkii/Quark and tell me more about the circumstances in which this happened? Were any of the players in the server in another dimension?
