### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by IchigoGames** [Quetzi/Morpheus#42]
Morpheus-1.12-3.3.2
Minecraft 1.12
Forge 2396
Crash report https://pastebin.com/kvUxsdNP 
this could be a mod in my pack makeing yours crash im not sure.

**Comment by Quetzi** [comment]
Not able to look into it more right now but that looks like a crash caused by some other mod shipping my api

**Comment by Quetzi** [comment]
Looks like this is caused by FuturePack: https://github.com/mcenderdragon/Futurepack-API/issues/209
