### ISSUE TITLE
Server Crash [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [Quetzi/Morpheus#43]
Good morning, I discovered that Morpheus is not compatible with VoidCraft mod.
My server crashes when I enter a dimension of that mod. Just to appear in that dimension closes and I can only take a step.
Below I show the versions that I use on the server.
Regards!

spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar
Morpheus-1.10.2-3.1.13.jar
VoidCraft-1.10.2-0.19.6.jar

CrashReport: https://pastebin.com/raw/PShNfNaH

**Comment by Quetzi** [comment]
It isn't voidcraft or Morpheus, the bug is in sponge.

**Comment by HeberonYT** [comment]
Thanks for the information, it was already reported
