### ISSUE TITLE
(1.12) Poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [Quetzi/Morpheus#44]
Hi ! My modpack crash with your mod (and some other mods but I'm going to advert other mods devs).
[crash-2017-07-17_11.03.47-client.txt](https://github.com/Quetzi/Morpheus/files/1152044/crash-2017-07-17_11.03.47-client.txt)

**Comment by Quetzi** [comment]
Scatter gun approach to trying to fix your crash is not the way to go

**Comment by Migmag789** [comment]
Wut, I don't speak english, so what does that mean ?

**Comment by Quetzi** [comment]
It means creating issues on trackers that don't have anything to do with the crash won't get you an answer any quicker

**Comment by Migmag789** [comment]
Okay ^^ But what is the real mod is crashing ?

**Comment by Migmag789** [comment]
But if many mods are crashing at the same time, and Morpheus are crashing with this other mods, why don't fix the issue ? o.O

**Comment by Quetzi** [comment]
Because you haven't reported an issue with Morpheus, or provided a log where Morpheus has crashed.

**Comment by Migmag789** [comment]
https://github.com/Quetzi/Morpheus/files/1152044/crash-2017-07-17_11.03.47-client.txt

**Comment by Migmag789** [comment]
o.O
