### ISSUE TITLE
1.12.1 After sleeping, day does not come.

### ISSUE THREAD

**Issue by ProsperCraft** [Quetzi/Morpheus#47]
![2017-09-06_12 42 45](https://user-images.githubusercontent.com/4427684/30129071-fa44fcc8-9301-11e7-9e6b-58e6737a55fe.png)

When you sleep, it says you are sleeping, it hits the required percent, then kicks everyone out of bed, and does not turn it to day.

version   1.12-3.3.2
forge-1.12.1-14.22.0.2469-universal.jar

**Comment by Quetzi** [comment]
I'd be interested to know which other mods are installed. My code doesn't do anything with players so if players are leaving their beds it is because the vanilla code thinks it is daytime. If there was a fundamental bug in the Morpheus it would have shown up before now.

**Comment by ProsperCraft** [comment]
[TownCraft-.04.zip](https://github.com/Quetzi/Morpheus/files/1282906/TownCraft-.04.zip)

Here is my work in progress pack, this is a Twitch export, feel free to hop on the server and check it out :)  Server address is built into the pack.

To import the profile- run the Twitch launcher, click mods, minecraft, click create custom profile, click on the nearly invisible import text at the top, click on the file, it will set up the pack and click play.

**Comment by Quetzi** [comment]
I'm not about to install an entire pack just to see which mods you are using. A list would have been more than enough. I don't see anything that indicates a problem with Morpheus so I'm closing until something is presented that shows otherwise.

**Comment by fedoranimus** [comment]
I am seeing a very similar issues on 1.12.2.

Players will jump in bed and the log will say it's morning, but it isn't actually morning. This message will keep looping as long as players stay in bed.

Here is my list of mods on a custom modpack
![image](https://user-images.githubusercontent.com/179260/32695438-f1426f32-c729-11e7-8866-dff7dde066bb.png)

Is there any additional information you require? Thanks!

**Comment by Quetzi** [comment]
Does it happen without Quark installed?

**Comment by fedoranimus** [comment]
If I remove Quark, I don't see it occuring. Might be related to [this](https://github.com/Vazkii/Quark/issues/575)?

**Comment by Quetzi** [comment]
Yes, Quark has attempted to duplicate Morpheus functionality and in-game it looks identical. You should be able to disable that module in quark though.
