### ISSUE TITLE
Doesn't work in our second dimension.

### ISSUE THREAD

**Issue by Saddestpanda** [Quetzi/Morpheus#48]
We started a server as a vanilla server and then later added mods to it and use a second dimension for materials rather than attempting to retro gen the original one. Everyone is required to sleep in the second dimension for night to pass. Even though the config is set to 1%.

**Comment by Quetzi** [comment]
This just means that the mod adding dimensions hasn’t added support for Morpheus. You might need to open it as a feature request for that mod.
