### ISSUE TITLE
Major Issues - No longer works serverside.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Quetzi/Morpheus#52]
Whenever placed a dedicated server you try and login and it says "Connection timeout" after like 5 mins. Download Recommended Forge
1.12.2 - 14.23.3.2655

**Comment by P3rf3ctXZer0** [comment]
There is no crash log. Also it may have something to do with the way forge changed the server side player sleep reg.

**Comment by caligator** [comment]
can verify-- I'm getting similar issues for my medium pop server I admin for; its causing some kind of server tick issue for certain players. 

https://hastebin.com/raxidadaca.sql

**Comment by Quetzi** [comment]
Is this a particular pack? I know Morpheus is in Continuum with the latest forge with no issues reported.

**Comment by P3rf3ctXZer0** [comment]
@Quetzi I am not a coder but I tested this by itself. Some players cannot sign in to the server when this mod is installed on both client and server. As modpack runners it doesn't make sense to try and leave this mod out especially when it works fine with line. check ()client.startup since forge changed the way it works in latest recommended and up.

**Comment by P3rf3ctXZer0** [comment]
Hopefully this helps.

**Comment by P3rf3ctXZer0** [comment]
any news on when this is getting fixed - this mod is very much needed.
