### ISSUE TITLE
[Bug] Sleep Voting doesn't work when in a non-default Overworld dimension

### ISSUE THREAD

**Issue by thefinaldegree** [Quetzi/Morpheus#53]
I run a server that is using [Just Enough Dimensions](https://minecraft.curseforge.com/projects/just-enough-dimensions) to provide a second Overworld dimension (Under DIM6).

When players sleep in this dimension, it shows the 'player is sleeping (1/2 50%)' message but even with the Sleep Percent set to 25% it requires all players in the dimension to be in bed, same as in Vanilla.

If you need any more information from me, let me know and I will be more than happy to provide.

**Comment by Quetzi** [comment]
I provide an api for mods to hook in to if they create new dimensions. It is on the author of Just Enough Dimensions to implement it.
