### ISSUE TITLE
PlayerWakeUpEvent not being called

### ISSUE THREAD

**Issue by MJRLegends** [Quetzi/Morpheus#56]
Hello, so in one of my mods i have code running in the PlayerWakeUpEvent, any chance Morpheus can call this event for the players being woken up?

As calling PlayerWakeUpEvent still seems the best option making Morpheus not need any special support straight away. Like i dont like the idea of creating i dont fancy creating 20+ classes for something i can do once in the PlayerWakeUpEvent or registering a class for every dimension in the game seems unnecessary 

Also if im registering handlers for dimensions, what if another mod wants to do that too...

**Comment by Quetzi** [comment]
Hi,

I don't think calling this event is within the scope of Morpheus. I don't actually ever make players wake up, the game does that itself when the time is no longer night. As such, if you find PlayerWakeUpEvent isn't being called, then it is likely another mod doing it as all Morpheus is doing is changing the time.

**Comment by MJRLegends** [comment]
I dont mean method overriding, Ok lets try this a different way, where is morpheus calling ForgeEventFactory#onPlayerWakeup or EntityPlayer#wakeUpPlayer which is where forge/vanilla fires the PlayerWakeUpEvent from?

**Comment by Quetzi** [comment]
It doesn't deal with waking up players **at **all****

**Comment by MJRLegends** [comment]
Then how can the PlayerWakeUpEvent be called?

**Comment by Quetzi** [comment]
I don't use that event, so I have no idea. Morpheus was written before that function was added to Forge, I've not switched to using it because the way I detect players waking up still works (and means I rely on less of Forge)

**Comment by MJRLegends** [comment]
Well rip any mod compact then

**Comment by Quetzi** [comment]
Essentially, Morpheus is just a tick handler that checks how many players are asleep and awake, then if it's 'night' calls the function registered to set the time to day for that dimension. I don't touch anything else.

**Comment by Rikshy** [comment]
Don't you think morpheus should still handle stuff the way the bed does? in terms of PlayerWakeUpEvent? I can't look into vanilla code atm and idk how it's the origin system also just sets the time. if no imho you should fire that event (it's not that big of a deal)

**Comment by MJRLegends** [comment]
Ok either way PlayerWakeUpEvent isnt being called, and no other mod is in my dev workspace other than mine. Im using forge events so i cant anymore than that

**Comment by MJRLegends** [comment]
Works without morpheus so im happy with my side of the event

**Comment by Rikshy** [comment]
@Quetzi just fire the event in the DefaultOverworldHandler and everything is good :)

**Comment by MJRLegends** [comment]
kk i will work it out then thanks

**Comment by Quetzi** [comment]
I could understand your issue being blamed on Morpheus if I was actually doing anything with waking players up, but I don't. The function in my code called wakeAllPlayers (or similar, I forget the exact name) doesn't actually wake players it just resets the array I track sleep status in. In terms of 'handling stuff the way the bed does' I already do that by letting the game handle that itself, I don't touch it. DefaultOverworldHandler doesn't deal with waking players up so calling the event there makes no sense at all and is actually likely to break more than it fixes.

**Comment by MJRLegends** [comment]
No problem thanks for your time i will work it out

**Comment by MJRLegends** [comment]
i believe my issue seems to be PlayerWakeUpEvent is only called client side with morpheus but server side with no morpheus installed

**Comment by MJRLegends** [comment]
I apologies for wasting your time ;)
