### ISSUE TITLE
[1.14.3] Server crash on player sleeping No such field error.

### ISSUE THREAD

**Issue by ProsperCraft** [Quetzi/Morpheus#60]
Console-
https://gist.github.com/ProsperCraft/fc24932f99e411021ba6108cc3f072d7

Crash log-
https://gist.github.com/ProsperCraft/b0ad4b10bab9dd4764a5df02853e2af7

Logs-
[latest.log](https://github.com/Quetzi/Morpheus/files/3353106/latest.log)
[debug.log](https://github.com/Quetzi/Morpheus/files/3353107/debug.log)

Modpack-
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by Quetzi** [comment]
Does this also happen on the latest supported version (1.14.2)?

**Comment by ProsperCraft** [comment]
Not sure as 1.14.2 is now gone the way of 1.8...left behind like a discarded old sock with holes.

**Comment by Quetzi** [comment]
Just submitted an update to 1.14.3 that should fix this
