### ISSUE TITLE
Feature request - Vote to NOT skip night

### ISSUE THREAD

**Issue by aaronhowser1** [Quetzi/Morpheus#63]
Basically adding -1 to the vote count, so you can actively try to keep it from skipping night aside from just not sleeping. This would be extremely useful for servers that have Astral Sorcery

**Comment by Quetzi** [comment]
This is already available. To vote to not skip the night you just don't get into bed, I think what you are requesting here is that voting to not sleep should count twice? It's also a perfectly valid configuration to include the mod and set the percentage required to 100% (the notifications themselves are quite useful).

**Comment by aaronhowser1** [comment]
My thinking was that simply not sleeping was more like not voting at all, while voting to not skip would be active participation to keep it night
