### ISSUE TITLE
alert not enabling by default

### ISSUE THREAD

**Issue by 2iguys** [Quetzi/Morpheus#64]
I have to do /morpheus alert every time i join cause it turns itself off.

**Comment by flipwalker42** [comment]
My server is also reporting this issue. 1.14.4, Forge version: 28.0.100, Morpheus version: 4.2.38

**Comment by 2iguys** [comment]
Update. As long as the server is running and hasn't been restarted it stays
enabled. But if I restart it turns back off again even with the config set
to on.

**Comment by Quetzi** [comment]
Fix for this has just been submitted to Curseforge, it should be live shortly (4.2.39)
