### ISSUE TITLE
[1.14.4] - Setting spawn during the day doesn't work

### ISSUE THREAD

**Issue by grundyboy34** [Quetzi/Morpheus#65]
The option in the config, AllowSetSpawnDaytime is set to true, but sneak right clicking beds doesn't set the players spawn, and only results in the vanilla message of "You can only sleep at night and during thunderstorms."

Morpheus 1.14.4 - 4.2.40  : server side only
forge 1.14.4 - 28.0.102

**Comment by Quetzi** [comment]
Fixed as of 4.2.41

**Comment by Quetzi** [comment]
You might find that this happens if you've moved your bed somewhere really close, I check if you are within 4 blocks of your existing spawn point, if you are you won't be able to set a new spawn point.

**Comment by grundyboy34** [comment]
Yeah I saw that part in the old code so I made sure to check further away, I've been trying anywhere between 10 to 30 blocks away from the old point.

**Comment by grundyboy34** [comment]
It is probably a good idea imo to get rid of the distance check and existing bed check. Just let them set a new spawn as long as they interact with a bed.

**Comment by grundyboy34** [comment]
The only check that needs to be done is that the bed they're interacting with isn't their already set bed so that they know it's their current respawn point.

**Comment by Quetzi** [comment]
Fixed in 4.2.42, note that sneak right click is specifically disabled from setting your spawn, right click normally.

**Comment by grundyboy34** [comment]
Thanks!
I will point out 1 caveat though and that is it'll set your spawn point and show the message on the same bed, given you right click the different halves. (So right click top of the bed, sets spawn, right click bottom, sets spawn, repeat.)
Other than that, it's working great!
Thanks again!
