### ISSUE TITLE
Feature Request: Add compatibility with Lord of the Rings Mod

### ISSUE THREAD

**Issue by andrewminer** [Quetzi/Morpheus#67]
I've created [a modpack](https://github.com/andrewminer/istari) for Minecraft 1.7.10 which includes both the Lord of the Rings (LotR) mod and Morpheus.  While Morpheus works as expected in the Overworld, the LotR mod has its own time system, and is unaffected.  By this, I mean that the server acts just as though Morpheus wasn't installed at all (i.e., all players must sleep for the night to pass).  Could you please add support for the Middle Earth dimension and its special time system?

**Comment by Quetzi** [comment]
The onus is on the author of that mod to add Morpheus support, there is a very easy to implement API that can be implemented by dimension adding mods.
