### ISSUE TITLE
RLCraft Server - Latest Update

### ISSUE THREAD

**Issue by DarkSanity96** [Quetzi/Morpheus#68]
Server wont let me run Morpheus on the server, every time i download and load it into the server, it says its the wrong mod - not sure if someone can help me here or not. thanks.

**Comment by Quetzi** [comment]
Whereabouts are you putting the jar?

**Comment by DarkSanity96** [comment]
in the mod folder

**Comment by DarkSanity96** [comment]
i got it to work
