### ISSUE TITLE
No wait time for sleep

### ISSUE THREAD

**Issue by Naxanria** [Quetzi/Morpheus#70]
If enough people have been reached for the sleeping, it skips the night almost instantly, making it nearly impossible to also sleep.
This is kinda needed as there are phantoms now.

**Comment by Quetzi** [comment]
Not entirely sure how this would work, the mod already alerts everyone when the first person sleeps. Issues with phantoms are a bit beyond the scope of what this mod was ever trying to do.

**Comment by Naxanria** [comment]
It shows the message at the moment it changes it to day. So you cant join in.

**Comment by Quetzi** [comment]
It sends a message whenever a players sleep state changes. If there is only 1 player required to sleep for a successful sleep vote then you might want to adjust the sleep percentage to better suit your requirements.
