### ISSUE TITLE
 NOT let me get out of bed

### ISSUE THREAD

**Issue by yordax89** [Quetzi/Morpheus#71]
Hello, I have a problem with my pack of mods, I have included the morpheus, and when I spend the night it doesn't let me get out of bed, I'm in version 1.12.2

![Screenshot_1](https://user-images.githubusercontent.com/31279886/69915031-5164da00-1429-11ea-8b9f-b28351a81b91.png)

**Comment by Quetzi** [comment]
Vanilla bug, completely unrelated to Morpheus.
