### ISSUE TITLE
Players sleeping message delay

### ISSUE THREAD

**Issue by AndresConforti** [Quetzi/Morpheus#72]
Hey there, somehow, wherever i or any of the players on the server goes to sleep, there is like a 5/8 second delay to display the default message (Amount of players sleeping)

Is there a solution for this?

Minecraft 1.12.2
ForgeEssentials, and a bunch more.
Morpheus-1.12.2-3.5.106

**Comment by Quetzi** [comment]
The message should be sent as soon as players are fully asleep. If you are experiencing a significant delay then it will be another mod causing it.
