### ISSUE TITLE
Mystcraft 1.6.4 Crashing on entering age

### ISSUE THREAD

**Issue by BongBingBing** [Quetzi/Morpheus#75]
So i made a private server for my friends and I and we're trying to get to a new dimension in mystcraft but every time we try and enter a new age the entire server crashes. I would really like to get to the other dimensions would appreciate any help I can get. 

[2020-03-23-7.log](https://github.com/Quetzi/Morpheus/files/4370815/2020-03-23-7.log)

**Comment by Quetzi** [comment]
Not sure why you posted that here, this is not the issue tracker for OTG Core.

**Comment by BongBingBing** [comment]
So where would that be exactly im very new here
