### ISSUE TITLE
Morpheus does not seem to calculate number of players correctly

### ISSUE THREAD

**Issue by JonoColwell** [Quetzi/Morpheus#76]
using Morpheus on a server for me and some mates, Version 1.15.2-4.2.50, the mod is only server side and doesn't seem to calculate the number of players correctly and have the correct percentage, seems to always calculate one less player than is online.

![image](https://user-images.githubusercontent.com/8704304/81178199-32c3ca00-8feb-11ea-80a2-3e23da075619.png)

**Comment by Quetzi** [comment]
You have the ignore miners function enabled and there is a miner.

**Comment by JonoColwell** [comment]
morpheus has not generated a config file and there's no /morpheus miners enable/disable option.

How do I disable this function?
