### ISSUE TITLE
[1.12.2] Players sleeping message appears at morning

### ISSUE THREAD

**Issue by LiskoSlayer63** [Quetzi/Morpheus#77]
When people go to sleep there is no sleeping message at all, but when the server skips the night the sleeping message shows at morning, just before the "wakey, wakey" text.

**Morpheus:** 3.5.106
**Forge:** 14.23.5.2847
**Sponge:** 1.12.2-2838-7.2.0

**At the morning this is shown (it says both at the same time):**
![kuva](https://user-images.githubusercontent.com/10125529/81452536-cafab400-918f-11ea-898f-d631c26642b4.png)

**Comment by Quetzi** [comment]
This is what you would expect. In this case one person is enough for the vote to pass, so when they sleep you get notified that they’ve slept and then that the sleep vote happened.
