### ISSUE TITLE
Can't sleep with one player

### ISSUE THREAD

**Issue by C0D33X** [Quetzi/Morpheus#79]
Can't sleep on my server when just one player are connected. 

MC Version: 1.15.2
Morpheus Version: 4.2.50 RELEASE

Obliging to type the command to spend the night.

**Comment by Quetzi** [comment]
In the event that only one player is online or in a dimension to sleep Morpheus does not interfere with anything, vanilla mechanics take over. If you are having any kind of issue sleeping with only one player online then it is some other mod causing the issue.
