### ISSUE TITLE
[1.12.2] Remove the account of players from the OP from the number of accounts during sleep.

### ISSUE THREAD

**Issue by MrLador** [Quetzi/Morpheus#80]
Remove the account of players from the OP from the number of accounts during sleep. A very necessary feature on servers with ghost mode in OP.

**Comment by Quetzi** [comment]
Players in creative mode are already not included in sleep voting.

**Comment by MrLador** [comment]
They are not counted, but they are counted in the dream message! I would like them to be omitted in the dream message at all
