### ISSUE TITLE
[1.12.2] Ability to remove the account of op players in the dream message.

### ISSUE THREAD

**Issue by MrLador** [Quetzi/Morpheus#81]
Op not counted, but they are counted in the dream message! I would like them to be omitted in the dream message at all.

There is an inviz op for players on the servers. They are not displayed online. The dream message shows them in its account of the number of players and percentages.

**Comment by Quetzi** [comment]
This is not a bug. If I displayed incorrect information in the alerts then that would be a bug. I don’t plan on introducing a bug just because it suits one persons use case, sorry.
