### ISSUE TITLE
[1.12.2] Support Galacticraft

### ISSUE THREAD

**Issue by Romz24** [Quetzi/Morpheus#82]
Please add support for the Galacticraft mod, at the moment there are 2 problems:
1. If you skip the night, does not drop radiation.
2. If you sleep in the [Cryogenic Chamber](https://wiki.micdoodle8.com/wiki/Cryogenic_Chamber), a message will appear in the chat several times that the player has gone to bed. Also, radiation is not reset during sleep if there are several people on the server.

**Comment by Quetzi** [comment]
Please request this on the Galacticraft tracker, I provide methods for dimension adding mods to add support.
