### ISSUE TITLE
Crash on launch [1.16.2]

### ISSUE THREAD

**Issue by Sunekaer** [Quetzi/Morpheus#83]
Crash on launch due to missing license in Mods toml

like https://github.com/Sunekaer/Flat-Bedrock/blob/ec0351b6a3105a76c520cfb010a59f39de8fa5a2/src/main/resources/META-INF/mods.toml#L4

https://paste.ee/p/OFIFt

**Comment by Quetzi** [comment]
Fixed in 4.2.58
