### ISSUE TITLE
Server List shows incompatible modlist message

### ISSUE THREAD

**Issue by TheMas3212** [Quetzi/Morpheus#86]
Server is running Forge 1.16.3-34.1.0
 - only mod is Morpheus 1.16.3-4.2.59

Client is running Forge 1.16.3-34.1.0
- no mods are installed
client shows imcompatible modlist message in server list
however client is able to connect without problem

**Comment by cpw** [comment]
Please fix this. There are plenty of examples of how to do this for forge > 1.13..

**Comment by Quetzi** [comment]
I remember spending many hours trying to figure this out in the past. In the end as it was non critical, I left it as is. I'm sure the solution is fairly simple, I just have no idea where to even start.

**Comment by cpw** [comment]
Would happily PR you some code, but this github is still only 1.12..

**Comment by Quetzi** [comment]
I moved to a private gitlab instance a while ago, I have pushed updated code to this repo now.
