### ISSUE TITLE
1.16+ Rain

### ISSUE THREAD

**Issue by Raycoms** [Quetzi/Morpheus#87]
Hi, I'm not entirely sure if this is caused by morpheus. 
But it appears that skipping the night with morpheus causes it to rain almost constantly on servers.

**Comment by Quetzi** [comment]
While Morpheus was resetting the rain, from 4.2.60 it should now do so more effectively.

**Comment by pupnewfster** [comment]
I don't think your fix [here](https://github.com/Quetzi/Morpheus/commit/3d8d38646b1630004c9052bb571b949cd74c6710#diff-9686758793ffc00e0ac90f90011b85f1107195f0cbda526d641f751c142e8c97R74) is actually quite right. This ends up calling this set of methods on the WorldInfo
```
setClearWeatherTime(0);
setRainTime(0);
setThunderTime(0);
setRaining(false);
setThundering(false);
```
Whereas vanilla when sleeping finishes calls these methods:
```
setRainTime(0);
setRaining(false);
setThunderTime(0);
setThundering(false);
```

I think the extra line/call to `setClearWeatherTime` zero overwrites whatever the current "forced clear" time is with zero ticks causing it to still rain more often than in vanilla. The simplest fix probably would be to mimic vanilla and instead do:

```java
if (world.getGameRules().getBoolean(GameRules.DO_WEATHER_CYCLE)) {
    ((ServerWorld) world).resetRainAndThunder();
}
```

Which is the same set of calls vanilla does post sleeping. Note: That the resetRainAndThunder method would need to be ATd to be accessible: `public net.minecraft.world.server.ServerWorld func_73051_P()V # resetRainAndThunder`. This would also I believe fix Morpheus changing the weather if doWeatherCycle is set to false given you don't have the gamerule check that vanilla makes.

**Comment by Quetzi** [comment]
`        if (world instanceof ServerWorld && world.getGameRules().getBoolean(GameRules.DO_WEATHER_CYCLE)) {
            ((ServerWorld) world).func_241113_a_(((ServerWorldInfo)world.getWorldInfo()).func_230395_g_(), 0, false, false);
        }`

Should achieve the same thing without the access transformer. Prior to 1.16 I used resetRainAndThunder but couldn't find the function in the initial 1.16 mappings. I'll add the game rule check, not including it would mean I break maps with permanent rain set...which while being quite unlikely to happen, could happen :)

**Comment by pupnewfster** [comment]
Ah ya I only recommended the AT because at a very brief glance (like 2 minutes long) I didn't see a way to get the world info.
