### ISSUE TITLE
Morpheus / Comforts Conflict

### ISSUE THREAD

**Issue by MWG-Logan** [Quetzi/Morpheus#94]
There is currently a conflict between Morpheus and the Comforts hammock.
The dev believes it is due to Morpheus not using a Forge hook that allows other mods to manipulate the time skip logic.
Please advise, as this breaks the skip-to-night mechanic of this mod.

**Comment by Quetzi** [comment]
Please explain the issue, my mod detects when a player is asleep, if the comforts mod does not set players to be asleep then I won't count them as being asleep.

**Comment by MWG-Logan** [comment]
It does count them as being asleep when you shift r-click, with the 'leave bed' button, chat, the Morpheus notification, and everything. I believe the actual conflict comes into play when Morpheus counts the players sleeping in hammocks during the day. Once the vote is passed, it looks as if Morpheus takes over and sets it to dawn, as opposed to dusk.

**Comment by Quetzi** [comment]
I provide an API for mods to use custom sleeping logic, like day sleeping.
