### ISSUE TITLE
Sleeping with one player online does nothing

### ISSUE THREAD

**Issue by sunnyughs** [Quetzi/Morpheus#97]
Forge - 36.1.2
Version - 1.16.5-4.2.70

When only one player is online on a server sleeping does nothing.

Also using `/morpheus version` returns "_@MCVERSION@-4.2.@BUILD@_"

**Comment by Quetzi** [comment]
Working as intended

**Comment by sunnyughs** [comment]
Solo player isnt allowed to sleep? Why is that?

**Comment by sunnyughs** [comment]
You cant even be bothered to explain "intended behavior"? lol

**Comment by Quetzi** [comment]
It's intended behaviour because it's a sleep vote mod. If one person sleeps then it's 100% of the vote and vanilla mechanics kicks in. It shouldn't need explaining because it's obvious.

**Comment by sunnyughs** [comment]
That's not what this bug was reported for. I'm saying nothing happens as in- the night doesnt end. The player just lays awake in the bed and no vote or vanilla mechanics kick in.

**Comment by Quetzi** [comment]
Oh, in that case it's still not Morpheus, it doesn't touch normal sleep mechanics. I just do what vanilla normally does early in some situations. It will be one of your other mods at fault.
